site_name: 操作系统实验文档
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
nav:
  - 主页: index.md
  - 实验环境搭建:
    - 主页: env/index.md
    - 开发环境配置:
      - Index: env/linux-setup.md
      - Remote: env/remote.md
      - Docker: env/docker.md
      - Windows:
        - VirtualBox: env/windows-virtualbox.md
        - VMWare: env/windows-vmware.md
        - WSL2: env/windows-wsl.md
      - macOS:
        - VirtualBox: env/macos-virtualbox.md
    - C 语言: env/c.md
    - Git: env/git.md
    - Qemu: env/qemu.md
    - Idea: env/neovim.md
    - GDB: env/gdb.md
  - 每周实验: 
    - Week 1: lab/lab1.md
    - Week 2: lab/lab1.md
    - Week 3: lab/lab1.md
    - Week 4: lab/lab1.md
    - Week 5: lab/lab1.md
    - Week 6: lab/lab1.md
    - Week 7: lab/lab1.md
    - Week 8: lab/lab1.md
    - Week 9: lab/lab1.md
    - Week 10: lab/lab1.md
    - Week 11: lab/lab1.md
    - Week 12: lab/lab1.md
    - Week 13: lab/lab1.md
    - Week 14: lab/lab1.md
    - Week 15: lab/lab1.md
    - Week 16: lab/lab1.md
  - 课程作业: 
    - HomeWork1: homework/homework1.md
  - 快速参考手册:
    - 目录: qrh/nav.md
  - 推荐阅读文献:
    - 某领域私货: reference/reference1.md
hooks:
  - scripts/hook.py
  # enable social to generate build sha in the right bottom cornor
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      cover_subtitle: genpdfversion
      jobs:
        - pdf: pdf/oslab-all.pdf
          include: .*
        - pdf: pdf/oslab-environment-setup.pdf
          include: env
        - pdf: pdf/oslab-quick-reference-handbook.pdf
          include: qrh
markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
repo_name: 'os-next-docs'
repo_url: 'https://github.com/yuk1i/os-next-docs'