site_name: 操作系统实验文档

theme:
  name: material
  language: zh
  user_color_mode_toggle: true
  custom_dir: overrides
  features:
    - navigation.tabs

nav:
  - 主页: zh/index.md
  - 实验环境搭建:
    - 主页: zh/env/index.md
    - 开发环境配置:
      - Index: zh/env/linux-setup.md
      - Docker: zh/env/docker.md
      - Windows:
        - VirtualBox: zh/env/windows-virtualbox.md
        - VMWare: zh/env/windows-vmware.md
        - WSL2: zh/env/windows-wsl.md
      - macOS:
        - VirtualBox: zh/env/macos-virtualbox.md
    - C 语言: zh/env/c.md
    - Git: zh/env/git.md
    - Qemu: zh/env/qemu.md
    - Idea: zh/env/neovim.md
    - GDB: zh/env/gdb.md
  - 每周实验: 
    - Week 1: zh/lab/lab1.md
    - Week 2: zh/lab/lab1.md
    - Week 3: zh/lab/lab1.md
    - Week 4: zh/lab/lab1.md
    - Week 5: zh/lab/lab1.md
    - Week 6: zh/lab/lab1.md
    - Week 7: zh/lab/lab1.md
    - Week 8: zh/lab/lab1.md
    - Week 9: zh/lab/lab1.md
    - Week 10: zh/lab/lab1.md
    - Week 11: zh/lab/lab1.md
    - Week 12: zh/lab/lab1.md
    - Week 13: zh/lab/lab1.md
    - Week 14: zh/lab/lab1.md
    - Week 15: zh/lab/lab1.md
    - Week 16: zh/lab/lab1.md
  - 课程作业: 
    - HomeWork1: zh/homework/homework1.md
  - 快速参考手册:
    - 目录: zh/qrh/nav.md
  - 推荐阅读文献:
    - 某领域私货: zh/reference/reference1.md

hooks:
  - scripts/hook.py
  # enable social to generate build sha in the right bottom cornor

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      cover_subtitle: genpdfversion
      jobs:
        - pdf: pdf/oslab-all.pdf
          include: .*
        - pdf: pdf/oslab-environment-setup.pdf
          include: env
        - pdf: pdf/oslab-quick-reference-handbook.pdf
          include: qrh

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_name: 'os-next-docs'

repo_url: 'https://github.com/yuk1i/os-next-docs'

extra:
    alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 简体中文
      link: /zh/ 
      lang: zh