site_name: 操作系统实验文档
repo_name: 'os-next-docs'
repo_url: 'https://github.com/yuk1i/os-next-docs'

theme:
  name: material
  language: zh
  logo: assets/logo.png
  user_color_mode_toggle: true
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # - pymdownx.tabbed:
  #     alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - 主页: index.md
  - 实验环境搭建:
    - Linux 环境: env/index.md
    - 开发环境配置: env/setup.md
    - 运行 Hello World: env/helloworld.md
  - 每周实验: 
    - Week 1 - 系统调用 Syscall: zh/lab/lab1.md
    - Week 2 - 静态链接: zh/lab/lab2.md
    - Week 3 - 裸机程序 Bare Metal: zh/lab/lab3.md
    - Week 4 - 中断 Interrupts: zh/lab/xv6lab-interrupts.md
    - Week 5 - 上下文切换 Context Switch: zh/lab/xv6lab-contextswitch.md
    - Week ? - 页表 Paging: zh/lab/xv6lab-paging.md
  - 课程作业: 
    - 第一次作业: zh/homework/homework1.md
  - 快速参考手册:
    - 目录: qrh/nav.md
    - GDB: qrh/gdb.md
    - Git: qrh/git.md
    - C 语言:
      - C 语言基础: qrh/c-basic.md
      - 静态链接: qrh/c-static-linking.md
  - 阅读材料:
    - 推荐文献: reference/reference1.md
  - 课程作业: 
    - 第一次作业: homework/homework1.md

hooks:
  - scripts/hook.py

plugins:
  - search
  # - info
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      cover_subtitle: genpdfversion
      jobs:
        - pdf: pdf/oslab-all.pdf
          include: .*
        - pdf: pdf/oslab-environment-setup.pdf
          include: env
        - pdf: pdf/oslab-quick-reference-handbook.pdf
          include: qrh

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - meta
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
    homepage: https://teecertlabs.com/
repo_name: 'os-next-docs'
repo_url: 'https://github.com/yuk1i/os-next-docs'

# extra:
#     alternate:
#     - name: English
#       link: en/ 
#       lang: en
#     - name: 简体中文
#       link: zh/ 
#       lang: zh
#     homepage: https://teecertlabs.com/
