site_name: 操作系统实验文档
repo_name: 'os-next-docs'
repo_url: 'https://github.com/yuk1i/os-next-docs'

theme:
  name: material
  language: zh
  logo: assets/logo.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true


nav:
  - 主页: index.md
  - 实验环境搭建:
    - 主页: env/index.md
    - Linux VM 搭建:
      - Windows + VMware: env/vm/windows-vmware.md
      - Windows + WSL (不推荐): env/vm/wsl.md
      - macOS + VMware: env/vm/macos.md
    - 手动环境配置: env/setup.md
    - VSCode 远程配置: env/vscode.md
    - 验证环境: env/helloworld.md
  - 每周实验: 
    - Week 1 - Linux基础: lab/lab1.md
    - Week 2 - C 语言基础及Makefile: lab/lab2.md
    - Week 3 - 裸机程序 Bare Metal: lab/xv6lab-baremetal.md
    - Week 4 - 陷入与中断 Trap & Interrupts: lab/xv6lab-interrupts.md
    - Week 5 - 上下文切换 Context Switch: lab/xv6lab-contextswitch.md
    - Week 6 - 内核页表 Kernel Paging: lab/xv6lab-paging.md
    - Week 7 - 用户空间 Userspace: lab/xv6lab-userspace.md
    - Week 8 - 进程 Process: lab/xv6lab-userprocess.md
    - Week 9 - 缺页异常 Page Fault: lab/xv6lab-pagefault.md
    - Week 10 - 互斥与同步 Mutual Exclusion & Synchronization: lab/xv6lab-sync.md
    - Week 11 - CPU Scheduling: lab/xv6lab-scheduling.md
    - Week 12 - 同步 2 Synchronization 2: lab/xv6lab-sync2.md
    
  - Weekly Lab Material:
    - Week 2 - C language basic & Makefile: laben/lab2.md
    - Week 3 - Bare Metal: laben/xv6lab-baremetal.md
    - Week 4 - Trap & Interrupt: laben/xv6lab-interrupts.md
    - Week 5 - Context Switch: laben/xv6lab-contextswitch.md
    - Week 6 - Kernel Paging: laben/xv6lab-paging.md
    - Week 7 - Userspace: laben/xv6lab-userspace.md
    - Week 8 - User Process: laben/xv6lab-userprocess.md
    - Week 9 - Page Fault: laben/xv6lab-pagefault.md
    - Week 10 - Mutual Exclusion & Synchronization: laben/xv6lab-sync.md
  - 快速参考手册:
    - 目录: qrh/nav.md
    - VisionFive2 板子教程: qrh/vf2.md
    - SSH & VSCode 远程配置: qrh/ssh-vscode.md
    # - GDB: qrh/gdb.md
    # - Git: qrh/git.md

hooks:
  - scripts/hook.py

plugins:
  - search
  - with-pdf:
      enabled_if_env: ENABLE_PDF_EXPORT
      cover: true
      custom_template_path: mkdocs-pdf-template
      verbose: true
      author: genpdfversion
      toc: false
      jobs:
        # - pdf: pdf/week1.pdf
        #   subtitle: Week 1 - 环境配置 & Linux 基础
        #   include: 
        #   - env
        #   - lab/lab1
        - pdf: pdf/lab2.pdf
          subtitle: Lab 2 - C 语言基础及Makefile
          include:
          - lab/lab2
        - pdf: pdf/lab2-en.pdf
          subtitle: Lab 2 - C language basic & Makefile
          include:
          - laben/lab2
        - pdf: pdf/lab3.pdf
          subtitle: Lab 3 - 裸机程序 Bare Metal
          include:
          - lab/xv6lab-baremetal
        - pdf: pdf/lab3-en.pdf
          subtitle: Lab 3 - Bare Metal
          include:
          - laben/xv6lab-baremetal
        - pdf: pdf/lab4.pdf
          subtitle: Lab 4 - 陷入与中断 Trap & Interrupt
          include:
          - lab/xv6lab-interrupts
        - pdf: pdf/lab4-en.pdf
          subtitle: Lab 4 - Trap & Interrupt
          include:
          - laben/xv6lab-interrupts
        - pdf: pdf/lab5.pdf
          subtitle: Lab 5 - 上下文切换 Context Switch
          include:
          - lab/xv6lab-contextswitch
        - pdf: pdf/lab5-en.pdf
          subtitle: Lab 5 - Context Switch
          include:
          - laben/xv6lab-contextswitch
        - pdf: pdf/lab6.pdf
          subtitle: Lab 6 - 内核页表 Kernel Paging
          include:
          - lab/xv6lab-paging
        - pdf: pdf/lab6-en.pdf
          subtitle: Lab 6 - Kernel Paging
          include:
          - laben/xv6lab-paging
        - pdf: pdf/lab7.pdf
          subtitle: Lab 7 - 用户空间 Userspace
          include:
          - lab/xv6lab-userspace
        - pdf: pdf/lab7-en.pdf
          subtitle: Lab 7 - Userspace
          include:
          - laben/xv6lab-userspace
        - pdf: pdf/lab8.pdf
          subtitle: Lab 8 - 用户进程 User Process
          include:
          - lab/xv6lab-userprocess
        - pdf: pdf/lab8-en.pdf
          subtitle: Lab 8 - User Process
          include:
          - laben/xv6lab-userprocess
        - pdf: pdf/lab9.pdf
          subtitle: Lab 9 - 缺页异常 Page Fault
          include:
          - lab/xv6lab-pagefault
        - pdf: pdf/lab9-en.pdf
          subtitle: Lab 9 - Page Fault
          include:
          - laben/xv6lab-pagefault
        - pdf: pdf/lab10.pdf
          subtitle: Lab 10 - 互斥与同步 Mutual Exclusion & Synchronization
          include:
          - lab/xv6lab-sync
        - pdf: pdf/lab10-en.pdf
          subtitle: Lab 10 - Mutual Exclusion & Synchronization
          include:
          - laben/xv6lab-sync
        - pdf: pdf/lab11.pdf
          subtitle: Lab 11 - 调度算法 CPU Scheduling
          include:
          - lab/xv6lab-sync
        # - pdf: pdf/oslab-quick-reference-handbook.pdf
        #   include: qrh

markdown_extensions:
  - admonition
  - footnotes
  - def_list
  - meta
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
    homepage: https://teecertlabs.com/
repo_name: 'os-next-docs'
repo_url: 'https://github.com/yuk1i/os-next-docs'

# extra:
#     alternate:
#     - name: English
#       link: en/ 
#       lang: en
#     - name: 简体中文
#       link: zh/ 
#       lang: zh
#     homepage: https://teecertlabs.com/
