name: ci 
on:
  workflow_dispatch:
  push:
    branches: 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install Chinese fonts
        run: |
          mkdir -p fonts && cd fonts
          pwd
          wget -O NotoSansCJK-TTF-VF.zip -nv https://github.com/notofonts/noto-cjk/releases/download/Sans2.004/02_NotoSansCJK-TTF-VF.zip
          unzip -n NotoSansCJK-TTF-VF.zip
          sudo cp Variable/TTF/NotoSansCJKsc-VF.ttf /usr/share/fonts/
          sudo cp Variable/TTF/Subset/NotoSansSC-VF.ttf /usr/share/fonts/
          sudo fc-cache -fv
          cd .. && rm -rf fonts
          ls -lha
      - name: Build
        run: | 
          mkdocs gh-deploy
          GITHUBCI=1 ENABLE_PDF_EXPORT=1 mkdocs build
      - name: Upload PDFs to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: site/pdf/**.pdf