name: pdf 
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true
      release_name:
        description: 'Release Name'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install CNS11643 fonts
        uses: RisingInIris2017/cjk-fonts-action@v1
      - name: Build PDF
        run: ENABLE_PDF_EXPORT=1 mkdocs build
      - name: Get current date
        id: vars
        run: echo "suffix=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}-${{ steps.vars.outputs.suffix }}
          name: ${{ github.event.inputs.release_name }}-${{ steps.vars.outputs.suffix }}
          draft: false
          prerelease: false
          files: site/pdf/**.pdf